import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import ClientLayout from "./ClientLayout";
import MessageWidget from '@/components/shared/MessageWidget';
import ChatbotWidget from '@/components/shared/ChatbotWidget';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { THEME } from "@/styles/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <AuthProvider>
          <Navbar />
          {/* <main className={`pb-24 bg-gradient-to-br ${THEME.colors.gradient.sky} min-h-screen`}></main> */}
          <main className="pb-24 min-h-screen">
            {children}
          </main>
          <Footer />
          <MessageWidget />
          <ChatbotWidget />
        </AuthProvider>
      </body>
    </html>
  );
}
